version: "3.9"

services:
  hazelcast:
    container_name: ngdangkietswe-hazelcast
    image: hazelcast/hazelcast:5.2.1
    ports:
      - "5701:5701"
  management-center:
    container_name: ngdangkietswe-hazelcast-management-center
    image: hazelcast/management-center:5.2.1
    ports:
      - "8080:8080"
    environment:
      MC_DEFAULT_CLUSTER: dev
      MC_DEFAULT_CLUSTER_MEMBER: hazelcast